controller_manager:
  ros__parameters:
    update_rate: 100 # Hz


    gripper_joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


    gripper_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController


gripper_joint_trajectory_controller:
  ros__parameters:
    joints:
      - gripper_joint_left_1

    write_op_modes:
      - gripper_joint_left_1
    
    interface_name: position

    command_interfaces:
      - position
    
    state_interfaces:
      - position
      - velocity

    state_publish_rate: 50.0 # Defaults to 50
    action_monitor_rate: 20.0 # Defaults to 20

    allow_partial_joints_goal: false # Defaults to false
    hardware_state_has_offset: true
    deduce_states_from_derivatives: true
    
    constraints:
      stopped_velocity_tolerance: 0.01 # Defaults to 0.01
      goal_time: 0.0 # Defaults to 0.0 (start immediately)



